### ISSUE TITLE
tensorflow  is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by brucelane** [martin-gorner/tensorflow-mnist-tutorial#2]
hello,
When I launch: sudo -H pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp35-cp35m-linux_x86_64.whl
I get on Ubuntu 64bit:
tensorflow-0.9.0rc0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
Thank you

**Comment by cmazeran** [comment]
Hey,
I encountered also this issue; might be due to an inconsistent version of python. After a few tries, this solution worked for me when using python 3.4 (using a different wheel):
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp35-cp35m-linux_x86_64.whl
sudo python3.4 -m pip install  $TF_BINARY_URL

**Comment by bcousson** [comment]
I'm facing the same issue. In fact cp35 means that the version is for CPython 3.5, using cp34 instead is fixing the install problem. There are as well some packages that are needed and not installed like python3-tk and python3-dev. That being said, the demo will not work since it seems to rely on Python 3.5 :-( which is not the default on latest ubuntu/mint distro.

**Comment by cmazeran** [comment]
If it can help: the demo is running for me with python 3.4 (on Ubuntu) with 2 small modifications on tensorflowvisu.py - look at my comment here:
https://github.com/martin-gorner/tensorflow-mnist-tutorial/commit/b010098ff0e4cddbc448fa4b24a5fec13e57ce31

**Comment by bcousson** [comment]
Thanks a lot, I've just seen that. It works as well. There is just a small typo in the fix (s/colour/colors/)

```
-        clist = rcParams['axes.prop_cycle']
+        colors = rcParams['axes.color_cycle']
         ccount = 1 if (colornum is None) else colornum
-        colors = clist.by_key()['color']
```

**Comment by brucelane** [comment]
I switched to a Mac, it works with Python 3.5 fyi
